backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
  - name: "photos"
    label: "Photos"
    folder: "pages/api/photos/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
  # - name: "categories"
  #   label: "Categories"
  #   files:
  #   - label: "Photo"
  #     name: "photo"
  #     file: "content/photo.md"
  #     fields:
  #       - { label: "Title", name: "title", widget: "string" }
  #       - { label: "Image", name: "image", widget: "image" }
  #       - { label: "Category", name: "category", widget: "string" }